drop table if exists sys_users;
drop table if exists sys_roles;
drop table if exists sys_permissions;
drop table if exists sys_users_roles;
drop table if exists sys_roles_permissions;

CREATE TABLE SYS_USERS
(
  ID       VARCHAR(64) PRIMARY KEY NOT NULL,
  USERNAME VARCHAR(100),
  PASSWORD VARCHAR(100),
  SALT     VARCHAR(100),
  LOCKED   BOOLEAN DEFAULT FALSE
);
CREATE UNIQUE INDEX IDX_SYS_USERS_USERNAME
  ON SYS_USERS (USERNAME);

CREATE TABLE SYS_ROLES
(
  ID          VARCHAR(64) PRIMARY KEY NOT NULL,
  ROLE        VARCHAR(100),
  DESCRIPTION VARCHAR(100),
  AVAILABLE   BOOLEAN DEFAULT FALSE
);
CREATE UNIQUE INDEX IDX_SYS_ROLES_ROLE
  ON SYS_ROLES (ROLE);


CREATE TABLE SYS_PERMISSIONS
(
  ID          VARCHAR(64) PRIMARY KEY NOT NULL,
  PERMISSION  VARCHAR(100),
  DESCRIPTION VARCHAR(100),
  AVAILABLE   BOOLEAN DEFAULT FALSE
);
CREATE UNIQUE INDEX IDX_SYS_PERMISSIONS_PERMISSION
  ON SYS_PERMISSIONS (PERMISSION);
